language: java
install: true
jdk: oraclejdk8
env:
  matrix:
  - TERM=dumb
before_script:
  - ./gradlew --version
script: ./gradlew build jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)